---
version: '3'

services:
  redis:
    image: docker.io/library/redis:7.0.8-alpine
    volumes:
      - type: volume
        source: redis-data
        target: /data
    ports:
      - target: 6379
        published: $REDIS_PORT
        protocol: tcp
    restart: unless-stopped
  meilisearch:
    image: docker.io/getmeili/meilisearch:v1.4.0
    hostname: meilisearch
    volumes:
      - type: volume
        source: meilisearch-data
        target: /meili_data
    environment:
      MEILI_HTTP_ADDR:
      MEILI_MASTER_KEY:
      MEILI_ENV:
      MEILI_NO_ANALYTICS:
    ports:
      - target: 7700
        published: $MEILI_HTTP_PORT
        protocol: tcp
    restart: unless-stopped
  postgres:
    image: docker.io/library/postgres:15.1-alpine
    hostname: postgres
    volumes:
      - type: volume
        source: postgresql-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - target: 5432
        published: $POSTGRES_PORT
        protocol: tcp
    restart: unless-stopped
  minio:
    image: docker.io/minio/minio:RELEASE.2023-09-23T03-47-50Z
    volumes:
      - type: volume
        source: minio-data
        target: /data
    environment:
      MINIO_ROOT_USER:
      MINIO_ROOT_PASSWORD:
    command: server /data --console-address ':9001'
    ports:
      - target: 9000
        published: $MINIO_PORT
        protocol: tcp
      - target: 9001
        published: $MINIO_WEB_PORT
        protocol: tcp
    restart: unless-stopped
  medusa-server:
    build:
      context: ./
    hostname: medusa-server
    environment:
      JWT_SECRET:
      COOKIE_SECRET:
      DATABASE_TYPE:
      DATABASE_URL:
      ADMIN_CORS:
      STORE_CORS:
      REDIS_URL:
    command: start
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
      - meilisearch
      - minio

volumes:
  redis-data:
    driver: local
  meilisearch-data:
    driver: local
  postgresql-data:
    driver: local
  minio-data:
    driver: local
